# Generated by Django 5.2.4 on 2025-07-25 10:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_alter_user_age_alter_user_gender_alter_user_phno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('users', models.ManyToManyField(blank=True, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
